# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import transaction_pb2 as pb_dot_transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/block.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0epb/block.proto\x12\x02pb\x1a\x14pb/transaction.proto\"\x83\x02\n\x0eUnsignedHeader\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x17\n\x0fprev_block_hash\x18\x02 \x01(\x0c\x12\x19\n\x11transactions_root\x18\x03 \x01(\x0c\x12\x12\n\nstate_root\x18\x04 \x01(\x0c\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x0e\n\x06height\x18\x06 \x01(\r\x12\x15\n\rrandom_beacon\x18\x07 \x01(\x0c\x12\x13\n\x0bwinner_hash\x18\x08 \x01(\x0c\x12#\n\x0bwinner_type\x18\t \x01(\x0e\x32\x0e.pb.WinnerType\x12\x11\n\tsigner_pk\x18\n \x01(\x0c\x12\x11\n\tsigner_id\x18\x0b \x01(\x0c\"H\n\x06Header\x12+\n\x0funsigned_header\x18\x01 \x01(\x0b\x32\x12.pb.UnsignedHeader\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"J\n\x05\x42lock\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12%\n\x0ctransactions\x18\x02 \x03(\x0b\x32\x0f.pb.Transaction*B\n\nWinnerType\x12\x12\n\x0eGENESIS_SIGNER\x10\x00\x12\x0e\n\nTXN_SIGNER\x10\x01\x12\x10\n\x0c\x42LOCK_SIGNER\x10\x02\x62\x06proto3')
  ,
  dependencies=[pb_dot_transaction__pb2.DESCRIPTOR,])

_WINNERTYPE = _descriptor.EnumDescriptor(
  name='WinnerType',
  full_name='pb.WinnerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GENESIS_SIGNER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TXN_SIGNER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_SIGNER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=456,
  serialized_end=522,
)
_sym_db.RegisterEnumDescriptor(_WINNERTYPE)

WinnerType = enum_type_wrapper.EnumTypeWrapper(_WINNERTYPE)
GENESIS_SIGNER = 0
TXN_SIGNER = 1
BLOCK_SIGNER = 2



_UNSIGNEDHEADER = _descriptor.Descriptor(
  name='UnsignedHeader',
  full_name='pb.UnsignedHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='pb.UnsignedHeader.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prev_block_hash', full_name='pb.UnsignedHeader.prev_block_hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactions_root', full_name='pb.UnsignedHeader.transactions_root', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_root', full_name='pb.UnsignedHeader.state_root', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pb.UnsignedHeader.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='pb.UnsignedHeader.height', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_beacon', full_name='pb.UnsignedHeader.random_beacon', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='winner_hash', full_name='pb.UnsignedHeader.winner_hash', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='winner_type', full_name='pb.UnsignedHeader.winner_type', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signer_pk', full_name='pb.UnsignedHeader.signer_pk', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signer_id', full_name='pb.UnsignedHeader.signer_id', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=304,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='pb.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unsigned_header', full_name='pb.Header.unsigned_header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='pb.Header.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=378,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='pb.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pb.Block.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactions', full_name='pb.Block.transactions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=454,
)

_UNSIGNEDHEADER.fields_by_name['winner_type'].enum_type = _WINNERTYPE
_HEADER.fields_by_name['unsigned_header'].message_type = _UNSIGNEDHEADER
_BLOCK.fields_by_name['header'].message_type = _HEADER
_BLOCK.fields_by_name['transactions'].message_type = pb_dot_transaction__pb2._TRANSACTION
DESCRIPTOR.message_types_by_name['UnsignedHeader'] = _UNSIGNEDHEADER
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.enum_types_by_name['WinnerType'] = _WINNERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnsignedHeader = _reflection.GeneratedProtocolMessageType('UnsignedHeader', (_message.Message,), dict(
  DESCRIPTOR = _UNSIGNEDHEADER,
  __module__ = 'pb.block_pb2'
  # @@protoc_insertion_point(class_scope:pb.UnsignedHeader)
  ))
_sym_db.RegisterMessage(UnsignedHeader)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'pb.block_pb2'
  # @@protoc_insertion_point(class_scope:pb.Header)
  ))
_sym_db.RegisterMessage(Header)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'pb.block_pb2'
  # @@protoc_insertion_point(class_scope:pb.Block)
  ))
_sym_db.RegisterMessage(Block)


# @@protoc_insertion_point(module_scope)
